{"name": "test_auth_code_negative", "status": "failed", "statusDetails": {"message": "AssertionError: assert 401 == 400\n  -401\n  +400", "trace": "self = <test_api.TestAPI object at 0x7f0904ed9a00>\napi = <api_client.ApiClient object at 0x7f0904d88c40>\n\n    @pytest.mark.API\n    def test_auth_code_negative(self, api):\n        \"\"\"\n        CHECK LOGIN PAGE RSPONSE CODE IF LOGIN IS FAIL\n    \n        Step 1:\n        Try to login via login page\n    \n        EXPECT: status_code == 400\n        \"\"\"\n        resp = api.login_user(\"QWERTY\", \"QWERTY\")\n>       assert resp.status_code == 400\nE       assert 401 == 400\nE         -401\nE         +400\n\ntest_api.py:195: AssertionError"}, "description": "\n        CHECK LOGIN PAGE RSPONSE CODE IF LOGIN IS FAIL\n        \n        Step 1:\n        Try to login via login page\n        \n        EXPECT: status_code == 400\n        ", "start": 1590595646331, "stop": 1590595646340, "uuid": "1e625ec5-fc0d-4e86-b1bf-caa7d2cafbef", "historyId": "4fbec46994823adec8231b013afab557", "testCaseId": "0953e688ac238857337105216c3538e0", "fullName": "test_api.TestAPI#test_auth_code_negative", "labels": [{"name": "tag", "value": "API"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestAPI"}, {"name": "host", "value": "alex-Z87X-UD3H"}, {"name": "thread", "value": "2999-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api"}]}